import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crypto Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("bg-[#E7EBF0] dark:bg-[#192028]")}>
        <ThemeProvider
        attribute="class"
        defaultTheme="light"
        enableSystem={false}
        storageKey="dashboard-theme"
       
        >{children}</ThemeProvider>
      </body>
    </html>
  );
}
